[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#4B5563"
font = "sans serif"

[server]
enableXsrfProtection = true

[browser]
gatherUsageStats = false 